### PR TITLE
Update tags for Stat 203, 300, 302, 305, and 443 questions

### PR DESCRIPTION
**Pull request by acyleung**
Tags have been added or updated for Stat 203, 300, 302, 305, and 443 questions according to the the revised taxonomy.

### CODE REVIEW

**Comment by xcompass** [comment]
@acyleung Thanks! Just one comment. Could you squash the commits into one?

**Comment by xcompass** [comment]
@acyleung I saw you have removed a few files. Any reason? If they are used in the course, it will cause problems.

**Comment by acyleung** [comment]
The files I removed should be all from Stat 203. Bruce and I went over the questions and we decided to delete some or merge some into one. I can squash the commits into one, except for the merge branch ones (I'm not sure including the merge branch one would cause any problem).

**Comment by xcompass** [comment]
@acyleung Thanks. It should be fine to include merged branch. Though, next time you may want to do a rebase if there are new commits in this repo. e.g. git pull origin --rebase. 

Also as for removing files, you may want to mark them as deprecated instead of remove them unless you are absolutely sure they are not being used currently and in the previous terms. As some of the instructor may access the old course for some references. Then he/she won't be able to access the deleted problems. But I think for 203 is fine. Only 2 courses in 2014. They were not using this library back then.

**Comment by acyleung** [comment]
Thanks @xcompass. I got it now. The commits are all squashed.

**Comment by xcompass** [comment]
Looks great! :+1:

**Comment by xcompass** [comment]
prod server is also updated.

**Pull request merged**
