### PR TITLE
Add Stat203 assignment

### PR DESCRIPTION
**Pull request by acyleung**
Upload Stat203 (Statistical methods for Pharmacy students) Assignment Questions

### CODE REVIEW

**Comment by xcompass** [comment]
Merged! Thanks!

**Comment by xcompass** [comment]
@acyleung any chance you can tag the problems? http://wiki.ubc.ca/Documentation:WeBWorK/How_to_Contribute_to_UBC_Library#Tag_Problems

**Comment by acyleung** [comment]
@xcompass  for sure. I will have to work with Bruce on this. I will update all the files later.

**Comment by acyleung** [comment]
@xcompass The Stat 203 and 305 questions that were merged have not yet available in the Open Problem Library. I would just like to double check on that, or am I missing anything?

**Comment by xcompass** [comment]
@acyleung my bad. It's updated now. Let me know if there is any problem.

**Pull request merged**
